
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /(.*\.svg)
  static_files: static/\1
  upload: static/(.*\.svg)
  mime_type: image/svg+xml

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
